server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: tick #placeholder
    url: jdbc:postgresql://postgres:5432/customer
    password: password #placeholder
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true